# Generated by Django 4.2.13 on 2024-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(unique=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='streamurl',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
